; resume.g
; called before a print from SD card is resumed
;
; generated by RepRapFirmware Configuration Tool on Fri Jul 13 2018 13:35:27 GMT+0200 (CEST)
G1 R1 X0 Y0 Z5 F6000 ; go to 5mm above position of the last print move
G1 R1 X0 Y0          ; go back to the last print move
M83                  ; relative extruder moves
G1 E10 F3600         ; extrude 10mm of filament
